services:
  postgres:
    image: postgres:16
    container_name: ruvds-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${Password}
      POSTGRES_DB: ${DB_NAME:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
